
[graph]
targets = [
    "aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"aarch64-unknown-linux-gnu",
	"x86_64-unknown-linux-gnu",
	"x86_64-unknown-linux-musl",
]
[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []